# The default build for wasp-os. Modify to customize your own build.
# At least one watch face must be specified. Quick ring apps will be added in order.

[[app]]
file = 'apps/bible.py'

[[app]]
file = 'apps/stopwatch.py'

[[app]]
file = 'apps/heart.py'

[[app]]
file = 'apps/alarm.py'

[[app]]
file = 'apps/timer.py'

[[app]]
file = 'apps/calculator.py'

[[app]]
file = 'apps/play2048.py'

[[app]]
file = 'apps/month.py'

[[watchface]]
file = 'watch_faces/clock.py'

[[watchface]] # Requires ClockApp to also be installed
file = 'watch_faces/week_clock.py'
default = true
